version: '3'
services:
  nodejs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    container_name: catalisa-api
    networks:
      - app-network
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: catalisa-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - myapp_postgres_data:/var/lib/postgresql/data

volumes:
  myapp_postgres_data:

networks:
  app-network:
    driver: bridge